parameters: 
  - name: ResourceGroupName
    default: '__ResourceGroupName__'
  - name: 'azureSubscription'
    default: '__azureSubscription__'
  - name: backendAzureRmResourceGroupName
    default: '__backendAzureRmResourceGroupName__'
  - name: backendAzureRmStorageAccountName
    default: '__backendAzureRmStorageAccountName__'
  - name: backendAzureRmContainerName
    default: '__backendAzureRmContainerName__'
  - name: backendAzureRmKey
    default: '__backendAzureRmKey__'
  - name: commandOptionsPlan
    default: '__commandOptionsPlan__'  
  - name: commandOptionsApply
    default: '__commandOptionsApply__' 

jobs:
- deployment: release_dev
  pool:
    vmImage: ubuntu-16.04
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: TerraformInstaller@0
          displayName: 'TF install'
          inputs:
            terraformVersion: '0.12.3'
        - task: TerraformTaskV1@0
          displayName: 'TF Initi'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: 'tf'
            backendServiceArm: ${{ parameters.azureSubscription }}
            backendAzureRmResourceGroupName: ${{ parameters.backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ parameters.backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ parameters.backendAzureRmContainerName }}
            backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
        - task: TerraformTaskV1@0
          displayName: 'TF Plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: 'tf'
            commandOptions: ${{ parameters.commandOptionsPlan }}
            environmentServiceNameAzureRM: ${{ parameters.azureSubscription }}
        - task: TerraformTaskV1@0
          displayName: 'TF Apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: 'tf'
            commandOptions: ${{ parameters.commandOptionsApply }}
            environmentServiceNameAzureRM: ${{ parameters.azureSubscription }}