stages:
- stage: Foundation
  #dependsOn: []
  ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:
    condition: and(succeeded(), true)
  ${{ if contains(variables['Build.SourceBranch'], 'hotfix') }}:  
    condition: false
  ${{ if contains(variables['Build.SourceBranch'], 'prod') }}:  
    condition: false
  ${{ if contains(variables['Build.SourceBranch'], 'qa') }}:  
    condition: false
  jobs:
    - template: JobFoundationAKS-tf.yaml
      parameters: 
        ResourceGroupName: '__ResourceGroupName'
        azureSubscription: '__azureSubscription__'
        backendAzureRmResourceGroupName: '__backendAzureRmResourceGroupName__'
        backendAzureRmStorageAccountName: '__backendAzureRmStorageAccountName__'
        backendAzureRmContainerName: '__backendAzureRmContainerName__'
        backendAzureRmKey: '__backendAzureRmKey__'
        commandOptionsPlan: '__commandOptionsPlan__'  
        commandOptionsApply: '__commandOptionsApply__' 