parameters: 
  - name: projectsolution
    default: 'HealthCheck/Pocs.HealthCheck/Pocs.HealthCheck.csproj'
  - name: argumentsbuild
    default: '/p:Configuration=Release --output=$(Agent.BuildDirectory)/Pocs.HealthCheck'

trigger:
  branches:
    include:
    - dev
    - qa
    - prod


stages:

- ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:  

  - template: Templates\StageAppSec.yaml
  - template: Templates\StageFoundation.yaml
  - template: Templates\StageBuildApp.yaml
    parameters: 
      projectsolution: ${{ parameters.projectsolution }}  
      argumentsbuild: ${{ parameters.argumentsbuild }}

  - stage: BuildImage
    displayName: Build-img
    dependsOn: BuildDev
    jobs:
    - job: Build
      pool:
        vmImage: ubuntu-16.04
      steps:
      #- checkout: self
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'Pocs.HealthCheck'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: Docker@2
        inputs:
          containerRegistry: 'pocraspacr'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: 'pocraspacr'
          repository: 'rasp'
          command: 'buildAndPush'
          Dockerfile: '$(System.ArtifactsDirectory)/Pocs.HealthCheck/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest

  - stage: DeployAKS
    dependsOn: BuildImage
    jobs:
    - deployment: release_dev
      ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:
        condition: and(succeeded(), true)
      ${{ if contains(variables['Build.SourceBranch'], 'hotfix') }}:  
        condition: false
      ${{ if contains(variables['Build.SourceBranch'], 'prod') }}:  
        condition: false
      ${{ if contains(variables['Build.SourceBranch'], 'qa') }}:  
        condition: false
      variables: 
        - name: ENVIRONMENT
          value: 'Development'
        - name: 'azureSubscription'
          value: 'Assinatura do Visual Studio Enterprise – MPN(a45048d3-69a8-4e2d-89a9-4585441c96f6)'

      pool:
        vmImage: ubuntu-16.04
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - script: echo running UnitTest
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Pocs.HealthCheck'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'AKSRASP'
                namespace: 'pocrasp'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(System.ArtifactsDirectory)/Pocs.HealthCheck/BuildImg-Container.yaml'
                secretType: 'dockerRegistry'
                containerRegistryType: 'Azure Container Registry'
