apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: template
  name: healthcheck
  labels:
    app: healthcheck
    produto: process
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
        produto: gamora
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: healthcheck
        image: pocraspacr.azurecr.io/rasp:{{TAG_VERSION}}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: k8s-secret

---
apiVersion: v1
kind: Service
metadata:
  name: svc-healthcheck
  namespace: template
  labels:
    app: healthcheck
    produto: process
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: healthcheck