apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: template
  labels:
    usage: pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: files-k8s
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: template
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv
---
apiVersion: v1
kind: Pod
metadata:
 name: azure-2
 namespace: template
spec:
 containers:
  - image: nginx
    name: azure-2
    volumeMounts:
      - name: azure
        mountPath: /api
 volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: pvc